--- Makefile_	2009-10-15 01:32:11.000000000 +0400
+++ Makefile	2009-10-15 01:33:13.000000000 +0400
@@ -48,14 +48,14 @@
 	@./$(APPL) -v | $(AWK) '{ print $$2; }' > $@
 
 install: compile .version
-	./mkinstalldirs $(prefix)/sbin
-	$(INSTALL) $(APPL) $(prefix)/sbin/$(APPL)-`cat .version`
-	rm -f $(prefix)/sbin/$(APPL)
-	(VER=`cat .version` ; cd $(prefix)/sbin ; ln -s $(APPL)-$$VER $(APPL) )
-	./mkinstalldirs $(MANDIR)/man8
-	$(INSTALL) -m 644 $(APPL).8 $(MANDIR)/man8/$(APPL).8
-	./mkinstalldirs $(CONFDIR)
-	$(INSTALL) -m 644 $(APPL).conf $(CONFDIR)/$(APPL).conf-dist
+	./mkinstalldirs $(DESTDIR)$(prefix)/sbin
+	$(INSTALL) $(APPL) $(DESTDIR)$(prefix)/sbin/$(APPL)-`cat .version`
+	rm -f $(DESTDIR)$(prefix)/sbin/$(APPL)
+	(VER=`cat .version` ; cd $(DESTDIR)$(prefix)/sbin ; ln -s $(APPL)-$$VER $(APPL) )
+	./mkinstalldirs $(DESTDIR)$(MANDIR)/man8
+	$(INSTALL) -m 644 $(APPL).8 $(DESTDIR)$(MANDIR)/man8/$(APPL).8
+	./mkinstalldirs $(DESTDIR)$(CONFDIR)
+	$(INSTALL) -m 644 $(APPL).conf $(DESTDIR)$(CONFDIR)/$(APPL).conf-dist
 
 clean:
 	rm -f *.[bo] unix/*.[bo] ntlm/*.[bo] *.BAK *.core *.obj *.err 
