# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

EAPI=6

# ebuild generated by hackport 0.5.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal git-r3

DESCRIPTION="Retry combinators for monadic actions that may fail"
HOMEPAGE="https://github.com/Soostone/retry"
EGIT_REPO_URI="https://github.com/Soostone/retry"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS=""
IUSE=""

RDEPEND="dev-haskell/data-default-class:=[profile?]
	>=dev-haskell/exceptions-0.5:=[profile?] <dev-haskell/exceptions-0.9:=[profile?]
	>=dev-haskell/random-1:=[profile?] <dev-haskell/random-1.2:=[profile?]
	<dev-haskell/transformers-0.6:=[profile?]
	>=dev-lang/ghc-7.6.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
	test? ( >=dev-haskell/hspec-1.9
		>=dev-haskell/hunit-1.2.5.2 <dev-haskell/hunit-1.4
		dev-haskell/mtl
		>=dev-haskell/quickcheck-2.7 <dev-haskell/quickcheck-2.9
		dev-haskell/stm )
"
