# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

EAPI=5

inherit git-r3

# ebuild generated by hackport 0.4.6

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="A (l29ah's fork of) library for parsing/printing the text/directory mime type"
HOMEPAGE="https://github.com/l29ah/mime-directory"
EGIT_REPO_URI="https://github.com/l29ah/mime-directory"

LICENSE="LGPL-2.1"
SLOT="0/${PV}"
KEYWORDS=""
IUSE=""

RDEPEND="dev-haskell/base64-string:=[profile?]
	dev-haskell/old-locale:=[profile?]
	>=dev-haskell/regex-pcre-0.94:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6.0
"
