# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

EAPI=5

# ebuild generated by hackport 0.4.6

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Proof assistant for Haskell using DataKinds & PolyKinds"
HOMEPAGE="http://hackage.haskell.org/package/equational-reasoning"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="|| ( ( >=dev-haskell/singletons-0.8:=[profile?] <dev-haskell/singletons-1.2:=[profile?] ) ( >=dev-haskell/singletons-2.0:=[profile?] <dev-haskell/singletons-2.1:=[profile?] ) )
	>=dev-haskell/tagged-0.6:=[profile?]
	>=dev-haskell/void-0.6:=[profile?] <dev-haskell/void-0.8:=[profile?]
	>=dev-lang/ghc-7.6.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
"
